// flow-typed signature: 7025b0f5288899ff1322f6b4910c07c7
// flow-typed version: <<STUB>>/attr-accept_v^1.1.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'attr-accept'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'attr-accept' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'attr-accept/dist/index' {
  declare module.exports: any;
}

declare module 'attr-accept/src/index' {
  declare module.exports: any;
}

declare module 'attr-accept/test/index' {
  declare module.exports: any;
}

declare module 'attr-accept/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'attr-accept/dist/index.js' {
  declare module.exports: $Exports<'attr-accept/dist/index'>;
}
declare module 'attr-accept/src/index.js' {
  declare module.exports: $Exports<'attr-accept/src/index'>;
}
declare module 'attr-accept/test/index.js' {
  declare module.exports: $Exports<'attr-accept/test/index'>;
}
declare module 'attr-accept/webpack.config.js' {
  declare module.exports: $Exports<'attr-accept/webpack.config'>;
}
