// flow-typed signature: 43dc83d9a1c86e197a229407e99716d3
// flow-typed version: <<STUB>>/express-fileupload_v^0.4.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-fileupload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-fileupload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-fileupload/lib/index' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/fileLimitUploads.spec' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/manual/manualtest' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/multipartFields.spec' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/multipartUploads.spec' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/options.spec' {
  declare module.exports: any;
}

declare module 'express-fileupload/test/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-fileupload/lib/index.js' {
  declare module.exports: $Exports<'express-fileupload/lib/index'>;
}
declare module 'express-fileupload/test/fileLimitUploads.spec.js' {
  declare module.exports: $Exports<'express-fileupload/test/fileLimitUploads.spec'>;
}
declare module 'express-fileupload/test/manual/manualtest.js' {
  declare module.exports: $Exports<'express-fileupload/test/manual/manualtest'>;
}
declare module 'express-fileupload/test/multipartFields.spec.js' {
  declare module.exports: $Exports<'express-fileupload/test/multipartFields.spec'>;
}
declare module 'express-fileupload/test/multipartUploads.spec.js' {
  declare module.exports: $Exports<'express-fileupload/test/multipartUploads.spec'>;
}
declare module 'express-fileupload/test/options.spec.js' {
  declare module.exports: $Exports<'express-fileupload/test/options.spec'>;
}
declare module 'express-fileupload/test/server.js' {
  declare module.exports: $Exports<'express-fileupload/test/server'>;
}
